version: '2'

services:
    api:
        image: hello-laravel
        container_name: hello-laravel-api
        build: .
        ports:
           - 8000:80
        volumes:
           - ./src/:/var/www/html
        links:
           - database
        depends_on:
           - database

    database:
        image: mysql:5.7
        container_name: db-mysql
        ports:
           - 3308:3306
        volumes:
           - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=hello-laravel

volumes:
    database: